apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: siteinfos.auditor.appscode.com
spec:
  group: auditor.appscode.com
  names:
    categories:
    - auditor
    - appscode
    - all
    kind: SiteInfo
    listKind: SiteInfoList
    plural: siteinfos
    singular: siteinfo
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          kubernetes:
            properties:
              cluster:
                properties:
                  displayName:
                    type: string
                  name:
                    type: string
                  provider:
                    enum:
                    - Aws
                    - Azure
                    - DigitalOcean
                    - GoogleCloud
                    - Linode
                    - Packet
                    - Scaleway
                    - Vultr
                    - BareMetal
                    - KIND
                    - Generic
                    - Private
                    type: string
                  uid:
                    type: string
                required:
                - uid
                type: object
              clusterName:
                type: string
              clusterUID:
                type: string
              controlPlane:
                properties:
                  dnsNames:
                    items:
                      type: string
                    type: array
                  emailAddresses:
                    items:
                      type: string
                    type: array
                  ipAddresses:
                    items:
                      type: string
                    type: array
                  notAfter:
                    format: date-time
                    type: string
                  notBefore:
                    format: date-time
                    type: string
                  uris:
                    items:
                      type: string
                    type: array
                required:
                - notAfter
                - notBefore
                type: object
              nodeStats:
                properties:
                  allocatable:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    type: object
                  capacity:
                    additionalProperties:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    type: object
                  count:
                    type: integer
                type: object
              version:
                properties:
                  buildDate:
                    type: string
                  compiler:
                    type: string
                  gitCommit:
                    type: string
                  gitTreeState:
                    type: string
                  gitVersion:
                    type: string
                  goVersion:
                    type: string
                  major:
                    type: string
                  minor:
                    type: string
                  platform:
                    type: string
                required:
                - buildDate
                - compiler
                - gitCommit
                - gitTreeState
                - gitVersion
                - goVersion
                - major
                - minor
                - platform
                type: object
            required:
            - nodeStats
            type: object
          metadata:
            type: object
          product:
            properties:
              licenseID:
                type: string
              productName:
                type: string
              productOwnerName:
                type: string
              productOwnerUID:
                type: string
              productUID:
                type: string
              version:
                properties:
                  commitHash:
                    type: string
                  commitTimestamp:
                    type: string
                  compiler:
                    type: string
                  gitBranch:
                    type: string
                  gitTag:
                    type: string
                  goVersion:
                    type: string
                  platform:
                    type: string
                  version:
                    type: string
                  versionStrategy:
                    type: string
                type: object
            required:
            - version
            type: object
        type: object
    served: true
    storage: true
