apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: redis-restore
spec:
  image: ghcr.io/kubestash/redis:v0.1.0-rc.0
  args:
    - restore
    - --namespace=${namespace:=default}
    - --restoresession=${restoreSession:=}
    - --snapshot=${snapshot:=}
    - --enable-cache=${enableCache:=}
    - --scratch-dir=${scratchDir:=}
    - --wait-timeout=${waitTimeout:=300}
    - --redis-args=${args:=}
