apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: volumesnapshot-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --task-name=${taskName:=}
  image: ghcr.io/kubestash/volume-snapshotter:v0.17.0
