apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: volumesnapshot-addon
spec:
  backupTasks:
  - name: VolumeSnapshot
    function: volume-snapshot-backup
    singleton: true
    driver: VolumeSnapshotter
    parameters:
    - name: snapshotClassName
      usage: The VolumeSnapshotClassName to be used by volumeSnapshot
      required: false
  restoreTasks:
  - name: VolumeSnapshotRestore
    function: volume-snapshot-restore
    driver: VolumeSnapshotter
    executor: Job
    singleton: true
