apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: volumesnapshot-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --volume-snapshot-class-name=${volumeSnapshotClassName:=}
  image: ghcr.io/kubestash/volume-snapshotter:v0.23.0
