{{ $ubi := .Values.distro.ubi }}
{{- if .Values.global }}
  {{ $ubi = default .Values.distro.ubi .Values.global.distro.ubi }}
{{- end }}

{{ if and .Values.kubevirt.enabled (not (eq $ubi "operator")) }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'kubevirt-logical-backup'
  labels:
    {{- include "kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - logical-backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=/kubestash-tmp}
  - --snapshot-ready-timeout=${snapshotReadyTimeout:=10m}
  image: '{{ include "image.ghcr" (merge (dict "_repo" "kubestash/kubevirt-plugin") $) }}:v0.1.0{{ include "catalog.ubi" $ }}'
{{ end }}
