{{ $ubi := .Values.distro.ubi }}
{{- if .Values.global }}
  {{ $ubi = default .Values.distro.ubi .Values.global.distro.ubi }}
{{- end }}

{{ if and .Values.kubevirt.enabled (not (eq $ubi "operator")) }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'kubevirt-restore'
  labels:
    {{- include "kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - logical-restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --components=${components:=}
  - --override-resources=${overrideResources:=false}
  image: '{{ include "image.ghcr" (merge (dict "_repo" "kubestash/kubevirt-plugin") $) }}:v0.1.0{{ include "catalog.ubi" $ }}'
{{ end }}
