{{- if eq (include "operator.enableTaskQueue" . | trim) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appscode:kubestash-task-queue
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch.k8s.appscode.com
    resources:
      - pendingtasks
    verbs: ["create", "get", "list", "watch", "patch"]
{{- end }}
