{{ $ubi := .Values.distro.ubi }}
{{- if .Values.global }}
  {{ $ubi = default .Values.distro.ubi .Values.global.distro.ubi }}
{{- end }}

{{ if and .Values.vault.enabled (not (eq $ubi "operator")) }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'vault-backup'
  labels:
    {{- include "kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --scratch-dir=${scratchDir:=/kubestash-tmp}
  - --enable-cache=${enableCache:=false}
  - --interim-data-dir=${interimDataDir:=/kubestash-interim}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --vault-args=${vaultArgs:=}
  - --key-prefix=${keyPrefix:=}
  image: '{{ include "image.ghcr" (merge (dict "_repo" "kubestash/vault") $) }}:v0.1.0{{ include "catalog.ubi" $ }}'
{{ end }}
