apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: manifest-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --include-rbac-resources=${includeRBACResources:=}
  image: ghcr.io/kubestash/manifest:v0.14.0
