apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: manifest-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:=300}
  image: ghcr.io/kubestash/manifest:v0.1.0