{{- if or .Values.apiserver.enableMutatingWebhook .Values.apiserver.enableValidatingWebhook }}
{{- if and (eq .Values.monitoring.agent "prometheus.io/operator") .Values.monitoring.operator }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubestash-operator.fullname" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubestash-operator.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kubestash-operator.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}
