{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-metrics-token" (include "kubestash-ui-server.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kubestash-ui-server.serviceAccountName" . }}
  labels:
    {{- include "kubestash-ui-server.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}
