apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubestash:ui:viewer
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - ui.kubestash.com
  resources:
  - "*"
  verbs: ["get", "list"]
