apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubestash.fullname" . }}-webhook-server
  namespace: {{ .Release.Namespace }}
  labels:
    kubestash.com/component: webhook-server
    {{- include "kubestash.labels" . | nindent 4 }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: admission
    port: 443
    targetPort: 8443
  # Port used to respond to Let's Encrypt HTTP challenges
  - name: acme
    port: 56791
    targetPort: 56791
  selector:
    kubestash.com/component: webhook-server
    {{- include "kubestash.selectorLabels" . | nindent 4 }}
