apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: vault-restore
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --scratch-dir=${scratchDir:=/kubestash-tmp}
  - --enable-cache=${enableCache:=false}
  - --interim-data-dir=${interimDataDir:=/kubestash-interim}
  - --wait-timeout=${waitTimeout:=300}
  - --vault-args=${vaultArgs:=}
  - --force=${force:=}
  - --key-prefix=${keyPrefix:=}
  - --old-key-prefix=${oldKeyPrefix:=}
  image: ghcr.io/kubestash/vault-restic-backup:v0.26.0-rc.0