{{ if .Values.kubedump.enabled }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: 'kubedump-addon'
  labels:
    {{- include "kubestash-catalog.labels" . | nindent 4 }}
spec:
  backupTasks:
  - driver: Restic
    executor: Job
    function: kubedump-backup
    name: manifest-backup
    parameters:
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    - default: ""
      name: ANDedLabelSelectors
      required: false
      usage: A set of labels, all of which need to be matched to filter the resources (comma-separated, e.g., 'key1:value1,key2:value2')
    - default: ""
      name: ORedLabelSelectors
      required: false
      usage: A set of labels, at least one of which need to be matched to filter the resources (comma-separated, e.g., 'key1:value1,key2:value2')
    - default: "false"
      name: IncludeClusterResources
      required: false
      usage: Specify whether to restore cluster scoped resources
    - default: ""
      name: IncludeNamespaces
      required: false
      usage: Namespaces to include in backup (comma-separated, e.g., 'default,kube-system')
    - default: ""
      name: ExcludeNamespaces
      required: false
      usage: Namespaces to exclude from backup (comma-separated, e.g., 'kube-public,temp')
    - default: ""
      name: IncludeResources
      required: false
      usage: Resource types to include in backup (comma-separated, e.g., 'pods,deployments')
    - default: ""
      name: ExcludeResources
      required: false
      usage: Resource types to exclude from backup (comma-separated, e.g., 'secrets,configmaps')
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
  restoreTasks:
  - driver: Restic
    executor: Job
    function: kubedump-restore
    name: manifest-restore
    parameters:
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    - default: ""
      name: ANDedLabelSelectors
      required: false
      usage: A set of labels, all of which need to be matched to filter the resources (comma-separated, e.g., 'key1:value1,key2:value2')
    - default: ""
      name: ORedLabelSelectors
      required: false
      usage: A set of labels, at least one of which need to be matched to filter the resources (comma-separated, e.g., 'key1:value1,key2:value2')
    - default: "false"
      name: IncludeClusterResources
      required: false
      usage: Specify whether to restore cluster scoped resources
    - default: ""
      name: IncludeNamespaces
      required: false
      usage: Namespaces to include in restore (comma-separated, e.g., 'default,kube-system')
    - default: ""
      name: ExcludeNamespaces
      required: false
      usage: Namespaces to exclude from restore (comma-separated, e.g., 'kube-public,temp')
    - default: ""
      name: IncludeResources
      required: false
      usage: Resource types to include in restore (comma-separated, e.g., 'pods,deployments')
    - default: ""
      name: ExcludeResources
      required: false
      usage: Resource types to exclude from restore (comma-separated, e.g., 'secrets,configmaps')
    - default: "false"
      name: OverrideResources
      required: false
      usage: Specify whether to override resources while restoring
    - default: ""
      name: StorageClassMappings
      required: false
      usage: Mapping of old to new storage classes (e.g., 'old1=new1,old2=new2')
    - default: "false"
      name: RestorePVs
      required: false
      usage: Specify whether to restore PersistentVolumes
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
{{ end }}

