apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: opensearch-backup
spec:
  image: ghcr.io/kubestash/elasticsearch:v0.1.0-rc.0
  args:
    - backup
    - --namespace=${namespace:=default}
    - --backupsession=${backupSession:=}
    - --enable-cache=${enableCache:=}
    - --scratch-dir=${scratchDir:=}
    - --wait-timeout=${waitTimeout:=300}
    - --os-args=${args:=}
    - --interim-data-dir=${interimDataDir:=}
