apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: kubedump-addon
spec:
  backupTasks:
  - name: manifest-backup
    function: kubedump-backup
    driver: Restic
    executor: Job
    singleton: true
    parameters:
    - name: enableCache
      usage: Enable or disable caching. Disabling caching may impact backup performance.
      required: false
      default: "true"
    - name: scratchDir
      usage: Directory for holding temporary files and restic cache.
      required: false
      default: /kubestash-tmp
    - default: ""
      name: ANDedLabelSelectors
      usage: A set of labels, all of which need to be matched to filter the resources (comma-separated, e.g., 'key1:value1,key2:value2')
      required: false
    - default: ""
      name: ORedLabelSelectors
      usage: A set of labels, at least one of which need to be matched to filter the resources (comma-separated, e.g., 'key1:value1,key2:value2')
      required: false
    - name: IncludeClusterResources
      default: "false"
      usage: "Specify whether to restore cluster scoped resources"
      required: false
    - name: IncludeNamespaces
      default: ""
      usage: Namespaces to include in backup (comma-separated, e.g., 'default,kube-system')
      required: false
    - name: ExcludeNamespaces
      default: ""
      usage: Namespaces to exclude from backup (comma-separated, e.g., 'kube-public,temp')
      required: false
    - name: IncludeResources
      default: ""
      usage: Resource types to include in backup (comma-separated, e.g., 'pods,deployments')
      required: false
    - name: ExcludeResources
      default: ""
      usage: Resource types to exclude from backup (comma-separated, e.g., 'secrets,configmaps')
      required: false
    volumeTemplate:
    - name: kubestash-tmp-volume
      usage: Holds temporary files and restic cache.
      source:
        emptyDir: {}
    volumeMounts:
    - name: kubestash-tmp-volume
      mountPath: /kubestash-tmp
  restoreTasks:
    - name: manifest-restore
      function: kubedump-restore
      driver: Restic
      executor: Job
      parameters:
        - default: "true"
          name: enableCache
          required: false
          usage: Enable or disable caching. Disabling caching may impact backup performance.
        - default: /kubestash-tmp
          name: scratchDir
          required: false
          usage: Directory for holding temporary files and restic cache.
        - default: ""
          name: ANDedLabelSelectors
          usage: A set of labels, all of which need to be matched to filter the resources (comma-separated, e.g., 'key1:value1,key2:value2')
          required: false
        - default: ""
          name: ORedLabelSelectors
          usage: A set of labels, at least one of which need to be matched to filter the resources (comma-separated, e.g., 'key1:value1,key2:value2')
          required: false
        - name: IncludeClusterResources
          default: "false"
          usage: "Specify whether to restore cluster scoped resources"
          required: false
        - name: IncludeNamespaces
          default: ""
          usage: Namespaces to include in restore (comma-separated, e.g., 'default,kube-system')
          required: false
        - name: ExcludeNamespaces
          default: ""
          usage: Namespaces to exclude from restore (comma-separated, e.g., 'kube-public,temp')
          required: false
        - name: IncludeResources
          default: ""
          usage: Resource types to include in restore (comma-separated, e.g., 'pods,deployments')
          required: false
        - name: ExcludeResources
          default: ""
          usage: Resource types to exclude from restore (comma-separated, e.g., 'secrets,configmaps')
          required: false
        - default: "false"
          name: OverrideResources
          usage: Specify whether to override resources while restoring
          required: false
        - default: ""
          name: StorageClassMappings
          usage: Mapping of old to new storage classes (e.g., 'old1=new1,old2=new2')
          required: false
        - default: "false"
          name: RestorePVs
          usage: Specify whether to restore PersistentVolumes
          required: false
      singleton: true
      volumeMounts:
        - mountPath: /kubestash-tmp
          name: kubestash-tmp-volume
      volumeTemplate:
        - name: kubestash-tmp-volume
          source:
            emptyDir: { }
          usage: Holds temporary files and restic cache.

