apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: kubedump-addon
spec:
  backupTasks:
  - name: manifest-backup
    function: kubedump-backup
    driver: Restic
    executor: Job
    singleton: true
    parameters:
    - name: enableCache
      usage: Enable or disable caching. Disabling caching may impact backup performance.
      required: false
      default: "true"
    - name: scratchDir
      usage: Directory for holding temporary files and restic cache.
      required: false
      default: /kubestash-tmp
    - name: sanitize
      default: "true"
      usage: Specify whether to remove the decorators from the resource YAML.
      required: false
    - name: includeDependants
      default: "false"
      usage: Specify whether to backup the dependants object along with their parent.
      required: false
    - name: labelSelector
      default: ""
      usage: Specify a label selector to filter the resources.
      required: false
    volumeTemplate:
    - name: kubestash-tmp-volume
      usage: Holds temporary files and restic cache.
      source:
        emptyDir: {}
    volumeMounts:
    - name: kubestash-tmp-volume
      mountPath: /kubestash-tmp
