apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: kubedump-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --and-label-selectors=${ANDedLabelSelectors:=}
  - --or-label-selectors=${ORedLabelSelectors:=}
  - --include-cluster-resources=${IncludeClusterResources:=}
  - --include-namespaces=${IncludeNamespaces:=}
  - --exclude-namespaces=${ExcludeNamespaces:=}
  - --include-resources=${IncludeResources:=}
  - --exclude-resources=${ExcludeResources:=}
  image: arnabbaishnab7620/kubedump:kubedump-restore_linux_amd641117