apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: kubedump-backup
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --sanitize=${sanitize:=true}
  - --label-selector=${labelSelector:=}
  - --include-dependants=${includeDependants:=false}
  image: ghcr.io/kubestash/kubedump:v0.1.0
