{{ if .Values.elasticsearch.enabled }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'elasticsearch-restore'
  labels:
    {{- include "kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --es-args=${args:={{ .Values.elasticsearch.args }}}
  - --interim-data-dir=${interimDataDir:=}
  image: '{{ include "image.ghcr" (merge (dict "_repo" "kubestash/elasticsearch") $) }}:v0.1.0-rc.0'
{{ end }}

