# Default values for kubestash-catalog.

proxies:
  ghcr: ghcr.io

# proxies:
#   ghcr: harbor.appscode.ninja/ghcr

# Number of seconds to wait for the database to be ready before backup/restore process.
waitTimeout: 300

elasticsearch:
  # If true, deploys Elasticsearch addon
  enabled: true
  # optional argument to send multielasticdump
  backup:
    # Arguments to pass to `multielasticdump` command  during backup process
    args: ""
  restore:
    # Arguments to pass to `multielasticdump` command during restore process
    args: ""
opensearch:
  # If true, deploys Opensearch addon
  enabled: true
kubedbmanifest:
  # If true, deploys KubeDBManifest addon
  enabled: true
kubedump:
  # If true, deploy kubedump addon
  enabled: true
  # Optional arguments to pass to the backup process
  backup:
    # Specify whether to remove the decorator
    sanitize: true
    # Specify label selector to filter resources
    labelSelector: ""
    # Specify whether to include the dependants resources along with it's parent
    includeDependants: false
mongodb:
  # If true, deploys MongoDB addon
  enabled: true
  # Maximum concurrency to perform backup or restore tasks
  maxConcurrency: 3
  # optional argument to send mongodump or mongorestore command
  backup:
    # Arguments to pass to `mongodump` command during backup process
    args: ""
  restore:
    # Arguments to pass to `mongorestore` command during restore process
    args: ""
mysql:
  # If true, deploys MySQL addon
  enabled: true
  # optional argument to send mysqldump or mysql command
  backup:
    # Arguments to pass to `mysqldump` command  during bakcup process
    args: ""
  restore:
    # Arguments to pass to `mysql` command during restore process
    args: ""
pvc:
  # If true, deploys PostgreSQL addon
  enabled: true
redis:
  # If true, deploys Redis addon
  enabled: true
  # optional argument to send redis-dump or redis command
  backup:
    # Arguments to pass to `redis-dump` command  during bakcup process
    args: ""
  restore:
    # Arguments to pass to `redis` command during restore process
    args: ""
volumesnapshot:
  # If true, deploys NATS addon
  enabled: true
workload:
  # If true, deploys ETCD addon
  enabled: true
