{{ if .Values.redis.enabled }}
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: 'redis-backup'
  labels:
    {{- include "kubestash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --redis-args=${args:={{ .Values.redis.args }}}
  image: '{{ include "image.ghcr" (merge (dict "_repo" "kubestash/redis") $) }}:v0.1.0-rc.0'
{{ end }}

